batman:
  swagger:
    title: api manage RESTful Content APIs
    description: <font color="red">接口文档</font>
    version: 1.0
    modules:
    - {
      model-name: serviceHi,
      packages: ["fast.cloud.nacos.servicehi.controller"],
      group-name: serviceHi
    }
logging:
  level:
    org.springframework: info